import type { Metadata } from "next";
import "./globals.css";

// 使用系统字体作为备选，避免Google Fonts连接问题
const systemFonts = {
  sans: [
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'sans-serif'
  ].join(', '),
  mono: [
    'SF Mono',
    'Monaco',
    'Inconsolata',
    'Roboto Mono',
    'Source Code Pro',
    'Menlo',
    'Consolas',
    'monospace'
  ].join(', ')
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{
          fontFamily: systemFonts.sans,
          '--font-geist-sans': systemFonts.sans,
          '--font-geist-mono': systemFonts.mono
        } as React.CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}
